# Trova la collatz più lunga sotto 1e6

def collatz(n):
    x = 1
    while n != 1:
        if n % 2 == 0:
            n = n // 2
        else:
            n = 3 * n + 1
        x += 1
    return x

x = 0
start = 0

for i in range(1, 1000001):
    if x < collatz(i):
        x = collatz(i)
        start = i

print("longest sequence is generated by", start)
